---
title: "COVID-19 BRASIL"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', out.width = '95%', echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
## Load Packages
library(dplyr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
library(stringr, warn.conflicts = FALSE)
library(leaflet, warn.conflicts = FALSE)
library(leaflet.extras, warn.conflicts = FALSE)
library(rgdal, warn.conflicts = FALSE)
library(ggplot2)
library(plotly)
library(gt)
library(directlabels)
library(ggrepel)
```

```{r, echo=FALSE}
## Load the Brazilian COVID data set
covid <- read.csv(
        "./data/HIST_PAINEL_COVIDBR_07set2021.csv",
        header = TRUE,
        sep = ";",
        dec = ",")
```

## Brasil - Situação em 07 de setembro de 2021.

```{r, echo=FALSE, warning=FALSE, fig.align='center', gtbl=TRUE}

## Cumulative COVID Cases in Brazil
casosAcumTab <- covid %>%
        filter(
                data == "2021-09-07",
                regiao == 'Brasil'
        ) %>%
        #mutate(Data = as.Date(data, "%Y-%m-%d")) %>%
        summarise(
                Casos_Acumulados = sum(casosAcumulado, na.rm = TRUE),
                                           
                Obitos_Acumulados = sum(obitosAcumulado, na.rm = TRUE),
                                           
                obitos_Novos = sum(obitosNovos, na.rm = TRUE),
                                     
                Casos_Novos = sum(casosNovos, na.rm = TRUE),
                             
                # Recuperadosnovos = formatC(sum(Recuperadosnovos, na.rm = TRUE),
                #                            big.mark = '.'),
                # emAcompanhamentoNovos = formatC(sum(emAcompanhamentoNovos, na.rm = TRUE),
                #                                 big.mark = '.')
        ) %>%
        mutate(Casos_Acumulados = as.numeric(as.character(Casos_Acumulados))) %>%
        mutate(Obitos_Acumulados = as.numeric(as.character(Obitos_Acumulados))) %>%
        mutate(obitos_Novos = as.numeric(as.character(obitos_Novos))) %>%
        mutate(Casos_Novos = as.numeric(as.character(Casos_Novos)))


gt(casosAcumTab) %>%
        fmt_number(
                columns = c(
                        'Casos_Acumulados', 'Casos_Novos', 'obitos_Novos', 
                        'Obitos_Acumulados'
                ),
                decimals = 0,
                sep_mark = '.'
        ) %>%
        cols_label( ## Change the names of the columns
                Casos_Acumulados = md('**Casos Confirmados**'),
                Casos_Novos = md('**Casos Novos**'),
                obitos_Novos = md('***obitos Novos***'),
                Obitos_Acumulados = md('**Obitos Acumulados**'),
                #Recuperadosnovos = md('**Casos Recuperados**')
                #emAcompanhamentoNovos = md('**Em Acompanhamento**')
        ) %>%
        tab_source_note(
                source_note = md("_Atualizado: 07/09/2021._")
        ) %>%
        tab_source_note(
                source_note = md("_Fonte: Secretarias Estaduais de Saúde. Brasil, 2021._")
        ) %>%
        # tab_style(
        #         cell_text(
        #                 align = "center", weight = "bold"
        #         ),
        #         locations = cells_summary(columns = T, rows = T)
        # ) %>%
        tab_options(
                ## Change the vertical lines
                
                ## change the 'Total' fields (summary)
                stub.font.weight = "bold",
                grand_summary_row.border.color = "black",
                ## change the column labels section
                column_labels.border.top.color = "black",
                column_labels.border.bottom.color = "black",
                column_labels.font.weight = "bold",
                table_body.vlines.color = "black",
                table.background.color = "#29a329",
                ## change the bottom of the body
                table_body.border.bottom.color = "black",
                table_body.border.top.color = "black",
                ## Change the bottom-most line or footnotes
                table.border.top.color = "black",
                table.border.bottom.color = "black",
                summary_row.border.color = "black",
        ) 


```


```{r, echo=FALSE}

## Plot Cumulative COVID Cases in Brazil
#text = paste('Data:', casosAcum$Data, '<br>', 'Casos Acumulados:', casosAcum$Casos_Acumulados)
casosAcum <- covid %>%
        filter(regiao == 'Brasil') %>%
        mutate(Data = as.Date(data, "%Y-%m-%d")) %>%
        select(Data, casosAcumulado)

ca <- ggplot(
        casosAcum,
        aes(Data, casosAcumulado)
        ) +
        geom_line(color = "#006400", size = 1.6) +
        geom_area(fill = "#69b3a2") +
        scale_x_date(
                date_labels = "%d/%m/%y", date_breaks = "1 month"
                ) +
        scale_y_continuous(
                breaks = seq(0, 22000000, by = 5000000),
                labels = scales::number_format(accuracy = 1,
                                               big.mark = '.',
                                               decimal.mark = ',')
                ) +
        theme(
                axis.text.x = element_text(angle = 50),
                axis.title = element_text(size = 14),
                plot.title = element_text(
                        hjust = 0.5, size = 14, face = "bold"),
                plot.caption = element_text(
                        size = 7, color = "blue", face = "italic")
                ) +
        labs(
                #title = "Casos Acumulados de COVID-19 no Brasil",
                x = "Data da notificação",
                y = "Casos Acumulados",
                caption = "Fonte: Secretarias Estaduais de Saúde. Brasil, 2021"
                )

ggplotly(ca)


```


## COVID nos Estados

```{r, echo=FALSE, comment='', warning=FALSE, message=FALSE}
R.utils::printf('\n\n')
## Summary data set per state
covid.states <- read.csv2('./output/covid_states.csv') %>%
        group_by(estado) %>%
        summarise(Casos_Acumulados = sum(Casos_Acumulados), Obitos_Acumulados = sum(Obitos_Acumulados)) %>%
        mutate(N = 1:n()) %>%
        select(4, 1, 2, 3)
        
tab.State <- covid.states %>%
        gt(rowname_col = 'N') %>%
        tab_stubhead(label = 'N') %>%
        fmt_number(
                columns = c('Casos_Acumulados', 'Obitos_Acumulados'),
                decimals = 0, 
                sep_mark = '.'
        ) %>%
        summary_rows(
                groups = NULL,
                columns = c('Casos_Acumulados', 'Obitos_Acumulados'),
                fns = list(TOTAL = 'sum'),
                formatter = fmt_number,
                decimals = 0,
                sep_mark = '.',
                use_seps = TRUE,
                missing_text = ""
        ) %>%
        cols_label(   
                N = md('**N**'),
                estado = md('**UF**'),
                Casos_Acumulados = md('**Casos Acumulados**'),
                Obitos_Acumulados = md('**Óbitos Acumulados**')
        ) %>%
        tab_source_note(
                source_note = md("_Fonte: Secretarias Estaduais de Saúde. Brasil, 2021._")
        ) %>%
        tab_source_note(
                source_note = md("_Atualizado: 07/09/2021._")
        ) %>%
        # tab_style(
        #         cell_text(
        #                 align = "center", weight = "bold"
        #         ),
        #         locations = cells_summary(columns = T, rows = T)
        # ) %>%
        tab_options(
                ## Change the vertical lines
                stub.border.color = "white",
                ## change the 'Total' fields (summary)
                stub.font.weight = "bold",
                grand_summary_row.border.color = "black",
                ## change the column labels section
                column_labels.border.top.color = "black",
                column_labels.border.bottom.color = "black",
                column_labels.font.weight = "bold",
                table_body.vlines.color = "black",
                table.background.color = "white",
                ## change the bottom of the body
                table_body.border.bottom.color = "black",
                table_body.border.top.color = "black",
                ## Change the bottom-most line or footnotes
                table.border.top.color = "black",
                table.border.bottom.color = "black",
                summary_row.border.color = "black",
        ) 

tab.State


```

## 

```{r, echo=FALSE, warning=FALSE, message=FALSE}

###***************************Ranking by States******************************###
## Cumulative COVID cases by Brazilian states
covid_states <- covid %>%
        filter(
                regiao != "Brasil",
                estado != "",
                municipio == '',
                is.na(codmun)
        ) %>%
        filter(data == "2021-09-07") %>%
        group_by(estado) %>%
        #distinct_all() %>%
        rename(
                Casos_Acumulados = casosAcumulado,
                Obitos_Acumulados = obitosAcumulado
        ) %>%
        arrange(desc(Casos_Acumulados, Obitos_Acumulados)) %>%
        select(estado, Casos_Acumulados, Obitos_Acumulados)

ranking <- covid_states[1:5, 1:2]

covid_UF <- covid %>%
        filter(
                regiao != "Brasil",
                #estado != "",
                municipio == '',
                is.na(codmun),
                estado %in% ranking$estado
        ) %>%
        mutate(Data = as.Date(data, "%Y-%m-%d")) %>%
        rename(UF = estado) %>%
        group_by(Data, UF) %>%
        distinct_all() %>%
        summarise(
                Casos_Acumulados = sum(unique(casosAcumulado), na.rm = TRUE),
                Obitos_Acumulados = sum(unique(obitosAcumulado), na.rm = TRUE),
                Casos_Novos = sum(unique(casosNovos, na.rm = TRUE))
        )
        
## Ranking of Accumulated COVID Cases by States
covidUFacc <- ggplot(
        covid_UF, aes(
                x = Data, y = Casos_Acumulados, 
                color = UF, group = UF
        )
) +
        geom_line(size = 0.8) +
        scale_x_date(
                date_labels = "%d/%m/%y", date_breaks = "3 weeks"
        ) +
        scale_y_continuous(
                labels = scales::label_number(big.mark = '.'), 
                breaks = seq(0, 5000000, by = 500000)
        ) +
        theme(
                axis.text.x = element_text(angle = 50),
                axis.title = element_text(size = 14),
                plot.title = element_text(
                        hjust = 0.5, size = 12, face = "bold"),
                plot.caption = element_text(
                        size = 7, color = "blue", face = "italic")
        ) +
        labs(
                title = "Rank dos Estados com Maiores Casos Acumulados de COVID-19",
                x = "Data da notificação",
                y = "Casos Acumulados",
                caption = "Fonte: Secretarias Estaduais de Saúde. Brasil, 2021"
        )
        

ggplotly(covidUFacc)


```
## 


```{r, echo=FALSE}
R.utils::printf('\n\n\n\n')
## Ranking of COVID Deaths by States
covidUFdeath <- ggplot(
        covid_UF, aes(
                x = Data, y = Obitos_Acumulados, 
                color = UF, group = UF
        )
) +
        geom_line(size = 0.8) +
        scale_x_date(
                date_labels = "%d/%m/%y", date_breaks = "3 weeks"
        ) +
        scale_y_continuous(
                labels = scales::label_number(big.mark = '.', decimal.mark = ','), 
                breaks = seq(0, 150000, by = 10000)
        ) +
        theme(
                axis.text.x = element_text(angle = 50),
                axis.title = element_text(size = 14),
                plot.title = element_text(
                        hjust = 0.5, size = 13, face = "bold"),
                plot.caption = element_text(
                        size = 7, color = "blue", face = "italic")
        ) +
        labs(
                title = "Rank dos Estados com Maiores Óbitos Acumulados por COVID-19",
                x = "Data da notificação",
                y = "Casos Acumulados",
                caption = "Fonte: Secretarias Estaduais de Saúde. Brasil, 2021"
        )

ggplotly(covidUFdeath)


```
## 


```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=''}
R.utils::printf('\n\n\n\n\n')
## Ranking of New COVID Cases by State
covidNewCases <- ggplot(
        covid_UF, aes(
                x = Data, y = Casos_Novos, color = UF
                )
        ) +
        geom_smooth(method = "gam", se = FALSE, size = 0.4) +
        scale_x_date(
                date_labels = "%d/%m/%y", date_breaks = "3 weeks"
        ) +
        scale_y_continuous(
                labels = scales::label_number(big.mark = '.', decimal.mark = ','), 
                breaks = seq(0, 65000, by = 2000)
        ) +
        theme(
                axis.text.x = element_text(angle = 50),
                axis.title = element_text(size = 14),
                plot.title = element_text(
                        hjust = 0.5, size = 13, face = "bold"),
                plot.caption = element_text(
                        size = 7, color = "blue", face = "italic")
        ) +
        labs(
                title = "Rank de Novos Casos de COVID-19 por Estado",
                x = "Data da notificação",
                y = "Casos Acumulados",
                caption = "Fonte: Secretarias Estaduais de Saúde. Brasil, 2021"
        )

ggplotly(covidNewCases)


```
## 

## Mapa de Calor para Mortes Acumuladas por Município

```{r, echo=FALSE, warning=FALSE, comment='', message=FALSE, fig.align='center'}
## Load the Brazilian COVID data set
covid_to_map <- read.csv2(
        './data/HIST_PAINEL_COVIDBR_07set2021.csv',
        header = TRUE,
        encoding = 'Windows-1252') %>% 
        filter(regiao != 'Brasil', municipio != '', estado != '') %>%
        rename(geocodigo = codmun)

## Read brazilian cities data set
cities <- read.csv(
        './data/spatial/brazilian_cities.csv',
        encoding = 'UTF-8'
) %>% rename(municipio = nome) %>%
        mutate(
                municipio = str_replace(
                        municipio, pattern = "''", replacement = "'"
                )
        ) %>%
        select(id, geocodigo, municipio, lng, lat)

## Merge the data sets
covid_cities <- covid_to_map %>%
        left_join(cities[-c(1, 2)], by = 'municipio', keep = FALSE) 
#head(covid_cities)

## Map
brazil <- readOGR('./data/brazil.shp', verbose = FALSE)

map_covid <- covid_cities %>%
        filter(data == '2021-09-07') %>%
        select(lat, lng, municipio, obitosAcumulado) %>%
        group_by(lng, lat, municipio) %>%
        summarise(totalDeaths = sum(obitosAcumulado, na.rm = TRUE)) %>%
        filter(!is.na(lng)) %>%
        filter(!is.na(lat)) %>%
        leaflet() %>%
        addTiles() %>%
        ## Set heatmap of COVID-19 in Brazil
        addHeatmap(
                lng = ~lng, lat = ~lat, intensity = ~totalDeaths, 
                blur = 20, max = 0.5, radius = 14
        ) %>%
        addCircles(
                lng = ~lng, lat = ~lat,
                label = ~totalDeaths,
                opacity = 0, fill = FALSE 
        ) %>%
        addLegend('bottomright',
                  values = ~totalDeaths, opacity = 1,
                  pal = colorNumeric(palette = 'RdYlBu',
                                     reverse = TRUE,
                                     domain = covid_cities$totalDeaths),
                  title = 'Total Deaths') %>%
        setView(lng = -50.80182849, lat = -11.00090426, zoom = 4) %>%
        ## Add Brazil boundary
        addPolygons(
                data = brazil, color = 'black', 
                fill = NA, 
                fillOpacity = 0.3
        ) %>%
        addTiles()

map_covid

```

